"""
generate_real_data_js.py
=========================
Generates web_real_data.js: one real UCI-HAR test subject's window data
plus the trained model (as base64-encoded ONNX), embedded as JS constants
so index.html can run the REAL trained model in-browser on REAL sensor
data -- not just the synthetic simulation.

Why embed instead of fetch() them at runtime? index.html is meant to work
as a plain double-clicked file:// page with no server. A <script src="...">
tag loads fine under file://; fetch()/XHR for local files does not (blocked
by the browser's same-origin policy). Embedding sidesteps that entirely.

Why subject 9 specifically? It's the smallest test subject (288 windows,
keeping the generated file's size down) while still covering a reasonable
spread of all 6 activity classes (42-52 windows per class).

Run:
    python train.py          # produces data/processed/har_cnn_uci.pt
    python export_onnx.py    # produces data/processed/har_cnn_uci.onnx
    python generate_real_data_js.py
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

from train import ACTIVITY_NAMES

DATA_DIR = Path("data/raw/uci_har/test")
ONNX_PATH = Path("data/processed/har_cnn_uci.onnx")
OUT_PATH = Path("web_real_data.js")
TARGET_SUBJECT = 9


def read_axis(name: str) -> list[list[float]]:
    with open(DATA_DIR / "Inertial Signals" / name) as f:
        # Rounded to 4 decimal places -- far more precision than a real
        # accelerometer has anyway, and it roughly halves the file size
        # versus the dataset's raw ~7-significant-digit formatting.
        return [[round(float(v), 4) for v in line.split()] for line in f]


def main() -> None:
    if not ONNX_PATH.exists():
        raise SystemExit(f"No ONNX model at {ONNX_PATH}. Run `python export_onnx.py` first.")

    with open(DATA_DIR / "subject_test.txt") as f:
        subjects = [int(line.strip()) for line in f if line.strip()]
    with open(DATA_DIR / "y_test.txt") as f:
        labels = [int(line.strip()) - 1 for line in f if line.strip()]

    x_all = read_axis("total_acc_x_test.txt")
    y_all = read_axis("total_acc_y_test.txt")
    z_all = read_axis("total_acc_z_test.txt")

    indices = [i for i, s in enumerate(subjects) if s == TARGET_SUBJECT]
    if not indices:
        raise SystemExit(f"No windows found for subject {TARGET_SUBJECT}")

    windows = [[x_all[i], y_all[i], z_all[i]] for i in indices]
    subj_labels = [labels[i] for i in indices]

    sample_payload = {"windows": windows, "labels": subj_labels, "subject_id": TARGET_SUBJECT}
    model_b64 = base64.b64encode(ONNX_PATH.read_bytes()).decode("ascii")

    lines = [
        "// Auto-generated by generate_real_data_js.py -- do not hand-edit.",
        "// Real UCI-HAR test-subject window data + the trained har_cnn_uci.onnx",
        "// model, both embedded so index.html can load and run the REAL trained",
        "// model in-browser without a server (a <script src> tag works under",
        "// file://; fetch() does not).",
        f"const REAL_ACTIVITY_NAMES = {json.dumps(ACTIVITY_NAMES)};",
        f"const REAL_SAMPLE_DATA = {json.dumps(sample_payload, separators=(',', ':'))};",
        f'const REAL_MODEL_BASE64 = "{model_b64}";',
    ]
    OUT_PATH.write_text("\n".join(lines))

    print(f"Subject {TARGET_SUBJECT}: {len(windows)} windows")
    label_counts = {ACTIVITY_NAMES[c]: subj_labels.count(c) for c in sorted(set(subj_labels))}
    print(f"Label distribution: {label_counts}")
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
